### ISSUE TITLE
Broken link: "pgAgent (RPM)" - "Yum HOWTO"

### ISSUE THREAD

**Issue by AnttiJalomaki** [pgadmin-org/pgaweb#11]
In the page: https://www.pgadmin.org/download/pgagent-rpm/ there is a link in broken with 404.
broken:
https://yum.postgresql.org/howtoyum.php
I believe correct would be:
https://yum.postgresql.org/howto/

This broken link can be found from GitHub pgadmin-www repo: https://github.com/pgadmin-org/pgadmin-www/blob/10f2959b2442f1896b458d916e9c58b268d673ce/download/linux4.php#L14C36-L14C74

**Comment by dpage** [comment]
Thanks, this has been fixed.

Please note that the pgadmin-www repo is an old version of the website. The current site is in this repo, and the link in question is actually stored in the backend database, not in the code.
