### ISSUE TITLE
Website/Documentation: release_notes missing

### ISSUE THREAD

**Issue by otheus** [pgadmin-org/pgaweb#5]
https://www.pgadmin.org/docs/pgadmin4/6.9/release_notes_6_9.html shows "404 Page not found". 

This is referenced by https://www.postgresql.org/about/news/pgadmin-4-v69-released-2450/

It there is a policy of obsoleting older versions and their documentations, please consider leaving their documentation or at least the release notes online for historical and compatibility reasons. Thank you.

**Comment by dpage** [comment]
I've moved this issue to the website repo.

It's not feasible to update the link, or to keep old doc versions on the website indefinitely. Instead, in commit [af36b7d](https://github.com/pgadmin-org/pgaweb/commit/af36b7d70e24941a707ab288e7ea4662c5f2084e) I've created a custom 404 page for the docs section of the website that will offer links of pages with the same name, but from current versions of the docs (where possible). That results in a 404 page such as:
<img width="1732" alt="Screenshot 2023-01-04 at 13 23 19" src="https://user-images.githubusercontent.com/316438/210564930-e4e306ca-5cd8-4a9b-89e2-f376fc167ecc.png">
Thanks for the report!
