### ISSUE TITLE
Website refers to dockerhub, and dockerhub refers back to website

### ISSUE THREAD

**Issue by lazynooblet** [pgadmin-org/pgaweb#8]
Just something I noticed today.

The container page on the website at https://www.pgadmin.org/download/pgadmin-4-container/ states:

> See the instructions on Docker Hub for information on running this container.

And Dockerhub at https://hub.docker.com/r/dpage/pgadmin4/ then states:
> See the website for documentation on deploying different versions of the container

Perhaps the website can refer to itself, or the container link just take you straight to the documentation.

**Comment by dpage** [comment]
Thanks, I've fixed the website.
