### ISSUE TITLE
FAQ has broken links

### ISSUE THREAD

**Issue by stefansundin** [pgadmin-org/pgaweb#9]
The FAQ page (https://www.pgadmin.org/faq/) has three links which are super annoying, because they seem to load forever and ever, making you think that the whole website is down, but there's something wrong on the server side causing the request to not result in a 404 error instead loading forever and ever.

The links are:

- https://www.pgadmin.org/docs/pgadmin4/dev/server_deployment.html
- https://www.pgadmin.org/docs/pgadmin4/dev/pgadmin_user.html
- https://www.pgadmin.org/docs/pgadmin4/dev/desktop_deployment.html

The links should have `/development/` instead of `/dev/`:

- https://www.pgadmin.org/docs/pgadmin4/development/server_deployment.html
- https://www.pgadmin.org/docs/pgadmin4/development/pgadmin_user.html
- https://www.pgadmin.org/docs/pgadmin4/development/desktop_deployment.html

PLEASE also make the bad links respond quicker with a 404 error. This was probably the most annoying part of this bug.

Thanks!

**Comment by stefansundin** [comment]
Testing with curl, I see that the `/dev/` links are trying to redirect to port 81, which does not work. That's probably something for your dev mode? I guess that redirect should be disabled in production then.

http://www.pgadmin.org:81/docs/pgadmin4/development/server_deployment.html

```
$ curl -v https://www.pgadmin.org/docs/pgadmin4/dev/server_deployment.html
> GET /docs/pgadmin4/dev/server_deployment.html HTTP/2
> Host: www.pgadmin.org
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/2 301
< server: nginx
< date: Tue, 30 Jan 2024 02:10:35 GMT
< content-type: text/html
< content-length: 162
< location: http://www.pgadmin.org:81/docs/pgadmin4/development/server_deployment.html
< x-varnish: 23875244 23475700
< age: 1168
< via: 1.1 varnish (Varnish/6.0)
< strict-transport-security: max-age=31536000
```

**Comment by dpage** [comment]
Thank you for the report. 

You actually hit a somewhat unusual set of circumstances, in which there were some URLs with once-correct-but-now-not paths, for which there was a very old redirect in place. Unfortunately, that redirect wasn't updated properly when the webserver was moved behind Varnish, and caused the attempt to connect to port 81 (which is not public).

I've just removed the redirects as they're so old that they're no longer required. You should now get a much more useful (and quick) 404 page if you try to visit the URLs in question.

**Comment by dpage** [comment]
Oh, and of course I've updated the links on the FAQ :-)
